name: my-env

channels:
  - conda-forge

dependencies:
  - python >=3.8
  - catch2 =3.4.0
  - pytest
  - numpy
  - eigen >=3.3.9
  - pybind11 >=2.10
  - cereal >= 1.3
  - nlopt >= 2.7
  - pytorch
  - cxx-compiler

